// src/components/ui/button.tsx
import * as React from "react"
import { Slot } from "@radix-ui/react-slot"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"

const buttonVariants = cva(
  "inline-flex items-center justify-center whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
        outline:
          "border border-input bg-background hover:bg-accent hover:text-accent-foreground",
        secondary:
          "bg-secondary text-secondary-foreground hover:bg-secondary/80",
        ghost: "hover:bg-accent hover:text-accent-foreground",
        link: "text-primary underline-offset-4 hover:underline",
      },
      size: {
        default: "h-10 px-4 py-2",
        sm: "h-9 rounded-md px-3",
        lg: "h-11 rounded-md px-8",
        icon: "h-10 w-10",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  }
)

interface ButtonProps
  extends React.ButtonHTMLAttributes<HTMLButtonElement>,
    VariantProps<typeof buttonVariants> {
  asChild?: boolean
}

const Button = React.forwardRef<HTMLButtonElement, ButtonProps>(
  ({ className, variant, size, asChild = false, ...props }, ref) => {
    const Comp = asChild ? Slot : "button"
    return (
      <Comp
        className={cn(buttonVariants({ variant, size, className }))}
        ref={ref}
        {...props}
      />
    )
  }
)
Button.displayName = "Button"

export { Button, buttonVariants }

// ui/src/lib/components/common/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import Spinner from './Spinner.svelte'

  interface Props {
    variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'danger'
    /** xs 24 px, sm 28 px, md 32 px, lg 36 px */
    size?: 'xs' | 'sm' | 'md' | 'lg'
    /** Square button holding only an icon; pass aria-label. */
    icon?: boolean
    disabled?: boolean
    loading?: boolean
    type?: 'button' | 'submit'
    title?: string
    'aria-label'?: string
    'aria-pressed'?: boolean
    'aria-expanded'?: boolean
    class?: string
    onclick?: (e: MouseEvent) => void
    children: Snippet
  }

  let {
    variant = 'primary',
    size = 'md',
    icon = false,
    disabled = false,
    loading = false,
    type = 'button',
    title,
    'aria-label': ariaLabel,
    'aria-pressed': ariaPressed,
    'aria-expanded': ariaExpanded,
    class: cls = '',
    onclick,
    children,
  }: Props = $props()

  const base =
    'inline-flex shrink-0 items-center justify-center gap-1.5 rounded-md font-medium whitespace-nowrap transition-colors duration-100 disabled:pointer-events-none disabled:opacity-50'

  const variants: Record<string, string> = {
    primary: 'bg-accent text-accent-fg hover:brightness-110 active:brightness-95',
    secondary: 'bg-surface-2 text-fg hover:bg-active',
    outline: 'border border-edge bg-transparent text-fg-2 hover:border-edge-strong hover:bg-hover hover:text-fg',
    ghost: 'text-fg-3 hover:bg-hover hover:text-fg',
    danger: 'bg-danger text-white hover:brightness-110 active:brightness-95',
  }

  const sizes: Record<string, [string, string]> = {
    xs: ['h-6 w-6', 'h-6 px-2 text-xs'],
    sm: ['h-7 w-7', 'h-7 px-2.5 text-xs'],
    md: ['h-8 w-8', 'h-8 px-3 text-[13px]'],
    lg: ['h-9 w-9', 'h-9 px-4 text-[13px]'],
  }
  const sizeClass = $derived(sizes[size][icon ? 0 : 1])
</script>

<button
  {type}
  {title}
  aria-label={ariaLabel}
  aria-pressed={ariaPressed}
  aria-expanded={ariaExpanded}
  aria-busy={loading || undefined}
  class="{base} {variants[variant]} {sizeClass} {cls}"
  disabled={disabled || loading}
  {onclick}
>
  {#if loading}
    <Spinner size="sm" class="h-3.5 w-3.5" />
  {/if}
  {@render children()}
</button>
